### ISSUE TITLE
Examples & Doc sites not working

### ISSUE THREAD

**Issue by oyeanuj** [rpearce/image-zoom#253]
This issue is a: 

- Bug report

It seems like Examples & Docs Github site is down. Could you see what might be going on?

Thank you!

**Comment by rpearce** [comment]
I changed the project name and forgot to change the link:
https://rpearce.github.io/image-zoom/

But be aware that everything will be changing in the near future:
https://github.com/rpearce/image-zoom/pull/244

**Comment by oyeanuj** [comment]
@rpearce Thanks for the new link! Curious what is the scope of the change - behavior, API or new features? The PR just indicates bugs being fixed..

**Comment by rpearce** [comment]
@oyeanuj check out this comment: https://github.com/rpearce/image-zoom/issues/227#issuecomment-634668215

**Comment by rpearce** [comment]
I'm getting back to it sometime today or tomorrow. There are some minor issues I need to sort out is all
