### ISSUE TITLE
Unable to get expected behavior with div having image as a background and other nested image

### ISSUE THREAD

**Issue by rjtbansal** [rpearce/image-zoom#267]
Here's my code snippet. Basically I have a `div` having background-image and within that div are few more divs wherein one has delete icon as well.
```
const backgroundImageStyle = imageUrl => ({
    backgroundImage: `url(${imageUrl})`,
    width: '202px',
    height: '144px',
    margin: '13px 24px 0px 0',
    display: 'flex',
    alignItems: 'flex-end',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    position: 'relative'
  });

<Zoom>
        <div className={styles.documentPhoto} key={id} style={backgroundImageStyle(url)}>
          { progress && (
              <div className={styles.overlay} />
          )}
          <div className={styles.infoBox}>
              { !progress && (
              <div className={styles.uploadedInfo}>
                  <CustomDeleteIcon onClick={onDeleteButtonClick} className={docEditStyles.deleteIcon} />
              </div>
              )}
          </div>
        </div>
</Zoom>
```

However upon rendering I see an odd button in the bottom. I was expecting for cursor to turn into zoom within the image.
![image](https://user-images.githubusercontent.com/8683116/107096123-03d7c000-67d8-11eb-81eb-880f4f396e83.png)

Upon clicking the zoomed image sticks to the bottom of the screen and doesn't zoom in as expected.
Any thoughts as to how to make it work with a snippet such as above? 

Also is there a way to see code snippets in storybook? I saw an example of div with images as background but was curious how it was implemented.

**Comment by rpearce** [comment]
It looks like you're not importing the CSS file that comes with version 4 of RMIZ.

If you read https://github.com/rpearce/image-zoom#basic-usage, you'll see:

```js
import 'react-medium-image-zoom/dist/styles.css'
```

That should get you on the right path, and should the source code for that story:

https://github.com/rpearce/image-zoom/blob/master/stories.js#L253

**Comment by rjtbansal** [comment]
Thanks @rpearce for your guidance. My bad that I missed styles.css as I was earlier using older version 3.x.

Zoom in and zoom out does happen but I have `CustomDeleteIcon` which is also an image as shown in code above. This leads to that icon also getting zoomed in. What I would like is to ignore that. Is it possible? Screenshot below after zoom in:
![image](https://user-images.githubusercontent.com/8683116/107121683-d6375900-6861-11eb-949c-0dfa5b391699.png)

**Comment by rpearce** [comment]
@rjtbansal In this version, `v4`, anything you place inside of `<Zoom>...</Zoom>` is going to get "zoomed". When I finish `v5`, this will change and be much more granular, but for what you are doing, you should only have your image as a child to the `<Zoom>` component.

Example:
```js
<div style="position:relative;">
  <Zoom>
    <div
      className={styles.documentPhoto}
      key={id}
      style={backgroundImageStyle(url)}
    />
  <Zoom>
  {/* overlay here */}
  {/* trash can here */}
</div>
```

To achieve what you are going for,
* only the image should be zoomable
* the white infobox should be a sibling element to the image that is placed on top of it
* the white infobox should get `pointer-events: none;`
* the trash can should be a sibling to these other two and should be absolutely positioned in the bottom right

* * *

I have never seen anyone try to do what you're doing before, but 👆 is how I would try to do it.

**Comment by rjtbansal** [comment]
Thanks @rpearce for your detailed explanation! Feel free to close the issue :)
