### ISSUE TITLE
Zoom UI Bug on iPhone

### ISSUE THREAD

**Issue by bitfede** [rpearce/image-zoom#268]
This issue is a: 

- Bug report

## Expected behavior
I expected the image to zoom full screen, like this:

<img width="862" alt="Screen Shot 2021-02-08 at 7 41 24 PM" src="https://user-images.githubusercontent.com/15684622/107299534-a779d800-6a45-11eb-900c-9fbcf2dbfe91.png">

## Actual behavior
What actually happened (ONLY ON IPHONES) is that the image is rendered behind the UI html elements. This only happens in iphones, here is a screenshot:

![IMG_7862](https://user-images.githubusercontent.com/15684622/107300590-d2fdc200-6a47-11eb-8182-812c1de358f0.PNG)

## Steps to reproduce behavior
1. First take an iphone
2. Then open an image inside a card html element

## Link to repository/example of behavior

Hard to recreate issue..

---

Just wondering if this happened to anyone on iphones, will try to get more testing to let you know if it's an issue with only one iphone or all types of iphones.

**Comment by rpearce** [comment]
@bitfede What does your code look like? A working example of the bug is easiest to debug, but if you can only share some code, I can try to help.

I'm guessing you are wrapping `<Zoom>` around the entire card when you really only want the image to zoom? But then why would it be behind?... 🤔 

* * *

On a related note, I'm working on the next version (gods, it is taking forever to get things right), but it's not ready yet.

**Comment by bitfede** [comment]
on my android it does not happen, it only happens on iphones, any browser.


I have a carousel component that has a render product images function inside
```jsx
          <Carousel renderIndicator={false} className={"imgTopPart"}>
            {renderProductImages(item.upc)}
          </Carousel>
```
and the function spits out this:
```js
  //renders the images
  const renderProductImages = (upc) => {
    // console.log(">>>>>>", images[upc]);
    let imgGallery = images[upc].map( (imgLink, i) => {
      return (
        <Zoom zoomMargin={50}>
          <div key={i} className={"productImgDesc"} style={{backgrundColor: 'white',backgroundImage: `url(https://cwc-product-images-s3-bucket.s3.amazonaws.com/${imgLink.Key })`}} />
        </Zoom>
      )
    })

    return imgGallery;

  }
```

the css class of the div is:
```css
.productImgDesc {
  width: 300px;
  height: 290px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
```

**Comment by rpearce** [comment]
@bitfede I'm fairly certain you would want `key={i}` to be passed to `<Zoom>` but that may be something unrelated.

* Are there absolutely positioned elements that are sitting on top of the image?
* Are there elements with `transforms` like `translateZ()` or `translate3d()` that are sitting on top of the image?

Without a functioning example of this issue, I'm afraid to say this will be incredibly difficult for me to debug.

**Comment by bitfede** [comment]
Yeah true, hard to debug without code. I appreciate the suggestions and I'll look into the things you suggested.

I was hoping this to be a known iphone-only bug/exception that had an easy CSS fix but I'll look into it more deeply.  Connecting the iphone with USB and using the browser dev tools remotely is my best bet.

Whenever I find the solution I'll write it down and close the issue. Thanks again for the assistance

**Comment by rpearce** [comment]
I also recommend using the iOS Simulator app that comes with XCode, opening Safari Dev Tools, and connecting the dev tools to that (if it's hard to do with a phone).

**Comment by rpearce** [comment]
I'm not sure how to resolve that at the moment other than disabling that animation style when the item is clicked.

**Comment by bitfede** [comment]
Yes that's the best thing to do, thanks man!!
