### ISSUE TITLE
npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/image-zoom#269]
This issue is a:

- Bug report

I recently upgraded to npm version `7.5.4`.

I believe the following error is caused by these [lines](https://github.com/rpearce/image-zoom/blob/master/package.json#L111-L113) not using `^`.

Is there a reason why specific versions are depended upon by this package?

I am currently using `npm install --legacy-peer-deps` as a workaround.

Thanks for this amazing package!

```console
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@">=16.x" from @fortawesome/react-fontawesome@0.1.14
npm ERR!   node_modules/@fortawesome/react-fontawesome
npm ERR!     @fortawesome/react-fontawesome@"^0.1.14" from the root project
npm ERR!   17 more (@sunknudsen/react-cms, react-dom, react-router-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-use@13.27.0
npm ERR! node_modules/react-medium-image-zoom/node_modules/react-use
npm ERR!   react-use@"13.27.0" from react-medium-image-zoom@4.3.1
npm ERR!   node_modules/react-medium-image-zoom
npm ERR!     react-medium-image-zoom@"^4.3.1" from @sunknudsen/react-optimized-image@0.1.0
npm ERR!     node_modules/@sunknudsen/react-optimized-image
npm ERR!       @sunknudsen/react-optimized-image@"git+ssh://git@react-optimized-image/sunknudsen/react-optimized-image.git#semver:^v0.1.0" from the root project
npm ERR!       1 more (@sunknudsen/react-cms)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sunknudsen/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunknudsen/.npm/_logs/2021-02-16T14_21_42_193Z-debug.log
```

**Comment by rpearce** [comment]
(Same as https://github.com/rpearce/image-zoom/issues/266)

Those should definitely be using the `^`. I wonder if that will actually fix the issue, though, since the error is talking about `peerDependencies` like `react`...

**Comment by ismay** [comment]
I encountered this as well. I suspect that this is happening because react-use (a dependency of this project) has an extra space in their react peerDependency definitions after v16 (before the `||`):

```
  "peerDependencies": {
    "react": "^16.8.0  || ^17.0.0",
    "react-dom": "^16.8.0  || ^17.0.0"
  },
```
> https://github.com/streamich/react-use/blob/master/package.json#L66-L67

So even though react 16.8+ and 17+ should both satisfy the range react-use is giving, npm 7 is not detecting react 17+ as valid, and because of that it's throwing an error stating that react v17 does not satisfy react-use's peer dependency requirements.

So seems like this is technically not a bug in this lib, but an upstream bug. Either in npm (not detecting the version after the OR), or in react-use's invalid version range definition.

**Comment by rpearce** [comment]
Let me see if I can update some dependencies in a patch release to make this go away...

**Comment by rpearce** [comment]
If any of you are interested, I started this "discussion" on "Where is v5?" I hope it sheds some light on things. https://github.com/rpearce/image-zoom/discussions/274

**Comment by rpearce** [comment]
@ismay I don't know what to say about that extra space for `react-use`. They have `1.8M` downloads per month, too, but it's not out of the realm of possibility. Maybe make a PR over there and see how it goes?

In the mean time, https://github.com/rpearce/image-zoom/pull/275 addresses @sunknudsen's `^` concern _except_ for `focus-options-polyfill`, for anything past version `1.2.0` breaks CI: https://github.com/calvellido/focus-options-polyfill/issues/16.

**Comment by ismay** [comment]
> @ismay I don't know what to say about that extra space for `react-use`. They have `1.8M` downloads per month, too, but it's not out of the realm of possibility. Maybe make a PR over there and see how it goes?

Yeah it seems like a long shot, and might not be the cause. But it was the only explanation I could find for npm not recognizing react 17 as a valid peerDependency 🤷‍♂️

**Comment by liliya-dev** [comment]
try to update node version to LTS version
