### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by elitan** [rpearce/image-zoom#270]
This issue is a **Feature request**.

## Description
It would be nice if it was possible to define the background color when zooming into an image to specify a different background image based on dark/light mode.

Right now the background seems to be hardcoded to light (https://github.com/rpearce/image-zoom/blob/deebc73e13973685ba2dcae4f6c51cc751cfa915/source/Controlled.tsx#L38-L39)

![2021-02-19 07 12 20](https://user-images.githubusercontent.com/331818/108465436-4db5b100-7282-11eb-9524-e0fa55ed0c9a.gif)

**Comment by rpearce** [comment]
@elitan Those are not hardcoded but _defaulted_ to those colors; you can override them with ease! Check it out:

```js
<RMIZ
  overlayBgColorEnd="rgba(0, 0, 0, 0.95)"
  overlayBgColorStart="rgba(0, 0, 0, 0)"
  {/*...*/}
/>
```

**Comment by elitan** [comment]
That worked perfectly. Thanks!

```jsx
      <Zoom
        overlayBgColorEnd="rgba(0, 0, 0, 0.75)"
        overlayBgColorStart="rgba(0, 0, 0, 0)"
      >
        <img src={src} alt={alt} />
      </Zoom>
```
