### ISSUE TITLE
Right-click copy <img>

### ISSUE THREAD

**Issue by mathew-kurian** [rpearce/image-zoom#271]
This issue is a: Question / support request

## Description
The medium.com implementation allows us to right-click and copy the image. However, this implementation (OOTB) doesn't allow to do so. Is there a way I can customize it to meet that feature as well?

**Comment by rpearce** [comment]
Not at the moment, and this won't be available until I can finish v5.

This is a duplicate of https://github.com/rpearce/image-zoom/issues/259, so I'm going to close this and track it through there.

**Comment by rpearce** [comment]
_Thank you_ for your patience, and this helps renew my effort.

**Comment by rpearce** [comment]
Update on v5 FYI: https://github.com/rpearce/image-zoom/discussions/274
