### ISSUE TITLE
Backport more flexible react dependency definition to v3.x

### ISSUE THREAD

**Issue by tommoor** [rpearce/image-zoom#277]
This issue is a:

- Other

## Description

Because much of the functionality of v3 is still not possible in v4 I (and maybe others) are staying with the v3 API for now. However the React dependencies are strictly scoped to v16. It would be lovely to get the work done here backported:

https://github.com/rpearce/image-zoom/commit/63e3aec02603e362b807bb627aa1c4e6a56a17e5#r48897317

**Comment by rpearce** [comment]
Thanks for making this issue! I'm hopping on it now.

**Comment by rpearce** [comment]
@tommoor Which bits of functionality are most valuable to you in v3? I ask so I can make sure to include the most critical things in v5. If I had to guess: the ability to replace the image with a higher-quality one?

**Comment by rpearce** [comment]
I've published `v3.1.3`. Can you try it and see if it's what you wanted? I had no problem installing it using a brand new `create-react-app`

**Comment by tommoor** [comment]
Looks to be good, warning is gone and functionality works 👍

**Comment by tommoor** [comment]
> Which bits of functionality are most valuable to you in v3?

`shouldRespectMaxDimension` is pretty important, we don't use the large image replacement, see:
https://github.com/outline/rich-markdown-editor/blob/main/src/nodes/Image.tsx#L226-L238

**Comment by rpearce** [comment]
Easy! That's one of my "must-have"s for v5.
