### ISSUE TITLE
Trouble with MDX and next/image

### ISSUE THREAD

**Issue by plainspace** [rpearce/image-zoom#278]
This issue is a question/support request.

Any tips on getting this working with MDX and [`next/image`](https://nextjs.org/docs/api-reference/next/image)? 

Added the following to MDXComponets.js:

```
import Zoom from 'react-medium-image-zoom' 

const MDXComponents = {
  Zoom
};
```

This is currently working in .md files with [`next/image`](https://nextjs.org/docs/api-reference/next/image):
```
<Image
      alt={`Image name`}
      src={`/static/path/to/image.png`}
      width={3360}
      height={2046}
    />
```

Expecting to be able to wrap 👆 in `<Zoom>...</Zoom>`

Getting the following error:

`TypeError: Cannot read property 'src' of undefined`

here:

```
const mdxSource = await renderToString(content, {
    components: MDXComponents,
    mdxOptions: {
      remarkPlugins: [
        require('remark-autolink-headings'),
        require('remark-slug'),
        require('remark-code-titles')
      ],
      rehypePlugins: [mdxPrism]
    }
  });
```

Any thoughts on how to resolve that?

**Comment by rpearce** [comment]
I've never used MDX or next, and there's a new version coming when I circle back to this project (see https://github.com/rpearce/image-zoom/discussions/274).

If you can provide a demo use case of the bug in an example project, I can take a look at it _and_ use it as a test case for v5.

**Comment by christianguevara** [comment]
This worked for me with MDX, not nextJS specific tho.

```js
<Zoom
          image={{
            src: props.src,
            alt: props.alt,
            className: `img`,
          }}
          zoomImage={{
            src: props.src,
            alt: props.alt,
            className: 'img--zoomed',
          }}
        />
```

**Comment by plainspace** [comment]
Thanks @christianguevara. That fixed it!
