### ISSUE TITLE
Outdated TypeScript types

### ISSUE THREAD

**Issue by mwanagosos** [rpearce/image-zoom#280]
Hello 😃 
Looks like it has been two years since the [@types/react-medium-image-zoom](https://www.npmjs.com/package/@types/react-medium-image-zoom) package has been updated. Is it still compatible with the 4th version of the [react-medium-image-zoom](https://www.npmjs.com/package/react-medium-image-zoom/v/4.3.3) library?

**Comment by rpearce** [comment]
I have no interaction with the `@types` project types, but this project should already be exporting its own TS types, so do you need that other one?

**Comment by rpearce** [comment]
Closing unless I hear back otherwise
