### ISSUE TITLE
Support custom overlay styles and blurring background effect

### ISSUE THREAD

**Issue by maticzav** [rpearce/image-zoom#292]
This issue is a:

- Feature request

## Description

It would be great if we could pass styles to the overlay. I really like the blur effect you can put on the background and right now it seems super hard to get that working. Having that in mind, a possible solution would be to add a `blur` option and go with a sensible default. Ideally, however, you could export a property `overlayStyle` that would let us pass extra styles to the overlay just like the `wrapperStyle` does.

**Comment by rpearce** [comment]
If this doesn't work for you, or there's something else amiss with it, I'm happy to reopen.

**Comment by rpearce** [comment]
This should be even easier with CSS now in `5.0.0`
