### ISSUE TITLE
is it possible to set a Scroll offset for image to load and unload?

### ISSUE THREAD

**Issue by m90khan** [rpearce/image-zoom#296]
I am using a locomotive scroll with has damping, so the scroll will continue a bit after leaving the mouse wheel. 

UnControlled Zoom: 
When I click on the image to zoom, it does not open unless the scrollbar is not moving at all. Is it possible to add a scroll offset such as when the event fired, the image opens even though there is still movement in the scrollbar?

Controlled Zoom: 
I rendered the controlled wrapper inside an array for every item. when I click on an image, the same image opens no matter which image I click. I got rid of the callback. any tip.

Thank you.

**Comment by rpearce** [comment]
@m90khan Thank you for opening this issue and taking the time to explain.

Your best bet for this is to indeed use the `ControlledZoom`, but I have a feeling that something isn't quite right with how you're using the library.

Can you please share an example of your code? Perhaps we can quickly sort it that way. If not, I'll need you provide a demo of the issue.

**Comment by m90khan** [comment]
Hey @rpearce,

Thank you for your reply. I added an example below. I think that I am making a mistake with handling the state.

`  import React, { useCallback, useState } from 'react';
import { Controlled as ControlledZoom } from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';

const MyComponent = (props) => {
  const { images } = props;
  const [isZoomed, setIsZoomed] = useState(false);

  const handleImgLoad = useCallback(() => {
    setIsZoomed(true);
  }, []);

  const handleZoomChange = useCallback((shouldZoom) => {
    setIsZoomed(shouldZoom);
  }, []);

  return (
    <>
      {images.map((el) => (
        <ControlledZoom isZoomed={isZoomed} onZoomChange={handleZoomChange}>
          <img
            alt="that wanaka tree"
            onLoad={handleImgLoad}
            src={`/path/to/${el}.jpg`}
            width="500"
          />
        </ControlledZoom>
      ))}
    </>
  );
};

export default MyComponent;

`

**Comment by m90khan** [comment]
`<img
alt="that wanaka tree"
onLoad={handleImgLoad}
src={/path/to/${el}.jpg}
width="500"
/>`

**Comment by rpearce** [comment]
@m90khan Yes, this should be simple to fix. Your state is only going to work for 1 element; instead, you need to have that state for _each one_.

This is completely untested, but here is the idea:

```js
import React, { useCallback, useState } from 'react';
import { Controlled as ControlledZoom } from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';

const MyComponent = (props) => {
  const { images } = props;

  return images.map((name) => (
    <MyImg key={name} name={name} />
  ));
};

const MyImg = (props) => {
  const { name } = props
  const [isZoomed, setIsZoomed] = useState(false);

  const handleImgLoad = useCallback(() => {
    setIsZoomed(true);
  }, []);

  const handleZoomChange = useCallback((shouldZoom) => {
    setIsZoomed(shouldZoom);
  }, []);

  return (
    <ControlledZoom isZoomed={isZoomed} onZoomChange={handleZoomChange}>
      <img
        alt="some good alt text here for each image please"
        onLoad={handleImgLoad}
        src={`/path/to/${name}.jpg`}
        width="500"
      />
    </ControlledZoom>
  )
}

export default MyComponent;
```

**Comment by rpearce** [comment]
The above 👆 should resolve this nicely. If it does not, I can reopen this, and we can figure it out.

**Comment by m90khan** [comment]
Thanks. I am going to test it and give feedback .
