### ISSUE TITLE
Right-click image "link" copy

### ISSUE THREAD

**Issue by developergunny** [rpearce/image-zoom#298]
I need the ability to copy image link with right click. Can it be?

**Comment by rpearce** [comment]
Hi and thanks for participating! I know this is an issue, and it's a duplicate of https://github.com/rpearce/image-zoom/issues/259.

When I am able to get back to this project, this will be handled. Until then, there's no way around it.

**Comment by developergunny** [comment]
Thanks:)

**Comment by rpearce** [comment]
This should now be resolved in `5.0.0`
