### ISSUE TITLE
Missing compatibility to react 18 and react-dom 18

### ISSUE THREAD

**Issue by edlerd** [rpearce/image-zoom#300]
The [package.json](https://github.com/rpearce/image-zoom/blob/main/package.json#L107) file in image-zoom limits to react 17 and react-dom 17, preventing an update to more recent versions of react 18.0, which was released earlier this week.

Please update the composer files and release a new version to unblock the update.

**Comment by rpearce** [comment]
Will get it done tomorrow evening. Thanks for the report.

**Comment by rpearce** [comment]
Didn't have time. Will look to do it tomorrow at some point.
