### ISSUE TITLE
React 18 compatibility

### ISSUE THREAD

**Issue by edlerd** [rpearce/image-zoom#305]
This issue is a: Bug report

## Expected behavior
I expected to be able to use React 18. 

## Actual behavior
image-zoom depends on react-use that is unmaintained and only supports react up to version 17.

## Solution
I propose to switch to https://github.com/alibaba/hooks which is well maintained and provides the same functionality as a drop-in replacement.

**Comment by rpearce** [comment]
Thanks for the heads up. I did not realize that react-use stopped getting updates since December. That's life sometimes. I'll see if we can just drop the dependency altogether.

**Comment by rpearce** [comment]
@edlerd If you get a minute, can you try version `4.4.0-rc.1` for me? If that works nicely for you, I'll promote that to `4.4.0`.

**Comment by edlerd** [comment]
Like a charm, no more warnings/conflicts on dependency resolution and feature wise everything still working. Good stuff :)

**Comment by rpearce** [comment]
@edlerd This should now be published under `v4.0.0`, and you've been added to the all-contributors list! Thank you for participating in this open source project.

<img width="414" alt="imagen" src="https://user-images.githubusercontent.com/592876/168299990-b3d8bb5d-65a9-4747-b77b-a8c8a1bbade7.png">
